name: desembale
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  camera: ^0.11.0+2
  cloud_firestore: ^5.4.3
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.1.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.7
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/onboarding/
    - assets/images/
  fonts:
    - family: Unbounded
      fonts:
        - asset: fonts/Unbounded/Unbounded-VariableFont_wght.ttf
    - family: Lexend_Deca
      fonts:
        - asset: fonts/Lexend_Deca/LexendDeca-VariableFont_wght.ttf

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#000000" # Fondo negro
  fullscreen: true # Asegura que la imagen cubra toda la pantalla
  image: assets/onboarding/splash.png # Ruta de la imagen que ocupará toda la pantalla
  android: true
  ios: true
